Repository niji-co/Fusion-Web, pull requests merged in 2021-04, with the labels that each got.

#4 Feature/projects/models
  .eslintrc.json
  .storybook/main.js
  .storybook/preview.js
  .vscode/settings.json
  package.json
  src/AppRoutes.tsx
  src/index.tsx
  src/pages/Project/Edit/EditProject.tsx
  src/pages/Project/Edit/index.ts
  src/pages/Project/Edit/style.css
  src/pages/Project/Project.tsx
  src/pages/Project/Row/ProjectRow.tsx
  src/pages/Project/Row/ProjectRowText.tsx
  src/pages/Project/Row/index.ts
  src/pages/Project/Row/services/IProjectRow.ts
  src/pages/Project/Row/services/IProjectRowText.ts
  src/pages/Project/Row/style.css
  src/pages/Project/index.ts
  src/pages/Project/services/IProject.ts
  src/pages/Project/services/projectReducer.ts
  src/pages/Project/services/projectSelector.ts
  src/pages/Project/style.css
  src/services/README.md
  src/services/actions/index.ts
  src/services/actions/inputActions.ts
  src/services/store.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/ProjectRow.stories.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  webpack.config.js
  yarn.lock
Labels: enhancement

#6 Features/projects/models
  src/pages/Project/Row/ProjectRowText.tsx
  src/pages/Project/Row/index.ts
  src/pages/Project/Row/models/ProjectRowFileProps.ts
  src/pages/Project/Row/models/ProjectRowImageProps.ts
  src/pages/Project/Row/models/ProjectRowVideoProps.ts
Labels: enhancement

#14 ✨ FEAT (Exhibition): create models & views
  src/pages/Exhibitions/Exhibition/index.ts
  src/pages/Exhibitions/Exhibition/models/ExhibitionProps.ts
  src/pages/Exhibitions/Exhibitions.tsx
  src/pages/Exhibitions/Role/Role.tsx
  src/pages/Exhibitions/Role/index.ts
  src/pages/Exhibitions/Role/models/RoleProps.ts
  src/pages/Exhibitions/Role/style.css
  src/pages/Exhibitions/Section/Section.tsx
  src/pages/Exhibitions/Section/index.ts
  src/pages/Exhibitions/Section/models/SectionProps.ts
  src/pages/Exhibitions/Section/style.css
Labels: Status: Pending, Type: Enhancement

#15 ➕ ADD: normalizr package
  package.json
  yarn.lock
Labels: Status: Accepted, Type: Enhancement

#17 🔨 REFACTOR: rename Asset to AssetModel
  src/models/Asset.ts
  src/models/AssetModel.ts
  src/pages/Project/Row/models/ProjectRowFileProps.ts
  src/pages/Project/Row/models/ProjectRowImageProps.ts
  src/pages/Project/Row/models/ProjectRowVideoProps.ts
Labels: Status: Review Needed, Type: Enhancement

#20 🐛 FIX: resolve wrong import statement for AssetModel
  src/stories/ProjectRow.stories.tsx
Labels: Status: Review Needed, Type: Bug

#18 ✨ FEAT: create Tag component
  src/components/README.md
  src/components/Tag/Tag.tsx
  src/components/Tag/index.ts
  src/components/Tag/models/TagProps.ts
  src/components/Tag/style.css
  src/pages/Project/ProjectPreviewLayout.tsx
Labels: Status: In Progress, Type: Enhancement
