Repository niji-co/Fusion-Web, pull requests merged in 2021-05, with the labels that each got.

#22 🔧 CONFIG: add path alias to root dirs
  .eslintrc.json
  package-lock.json
  tsconfig.json
Labels: Status: Review Needed, Type: Enhancement

#23 👷 CI: create eslint test
  .github/workflows/ci-eslint.yml
  package-lock.json
Labels: Status: Review Needed, Type: Enhancement

#25 chore: move stories out of src
  src/pages/Exhibitions/Role/Role.tsx
  stories/Button.stories.tsx
  stories/Button.tsx
  stories/Header.stories.tsx
  stories/Header.tsx
  stories/Introduction.stories.mdx
  stories/Page.stories.tsx
  stories/Page.tsx
  stories/ProjectRow.stories.tsx
  stories/assets/code-brackets.svg
  stories/assets/colors.svg
  stories/assets/comments.svg
  stories/assets/direction.svg
  stories/assets/flow.svg
  stories/assets/plugin.svg
  stories/assets/repo.svg
  stories/assets/stackalt.svg
  stories/button.css
  stories/header.css
  stories/page.css
Labels: Status: Review Needed, Type: Enhancement

#21 🔨 REFACTOR: refactoring project module
  .eslintrc.json
  package-lock.json
  package.json
  src/AppRoutes.tsx
  src/components/Tag/Tag.tsx
  src/dev/server.ts
  src/pages/Project/Edit/EditProject.tsx
  src/pages/Project/Edit/index.ts
  src/pages/Project/Edit/style.css
  src/pages/Project/Project.tsx
  src/pages/Project/ProjectPreviewLayout.tsx
  src/pages/Project/Row/ProjectRow.tsx
  src/pages/Project/Row/ProjectRowFile.tsx
  src/pages/Project/Row/ProjectRowImage.tsx
  src/pages/Project/Row/ProjectRowText.tsx
  src/pages/Project/Row/ProjectRowVideo.tsx
  src/pages/Project/Row/index.ts
  src/pages/Project/Row/models/ProjectRowFileModel.ts
  src/pages/Project/Row/models/ProjectRowFileProps.ts
  src/pages/Project/Row/models/ProjectRowImageModel.ts
  src/pages/Project/Row/models/ProjectRowImageProps.ts
  src/pages/Project/Row/models/ProjectRowModel.ts
  src/pages/Project/Row/models/ProjectRowProps.ts
  src/pages/Project/Row/models/ProjectRowTextModel.ts
  src/pages/Project/Row/models/ProjectRowTextProps.ts
  src/pages/Project/Row/models/ProjectRowVideoModel.ts
  src/pages/Project/Row/models/ProjectRowVideoProps.ts
  src/pages/Project/Row/services/projectRowSelectors.ts
  src/pages/Project/models/ProjectProps.ts
  src/pages/Project/services/fakeProjectAPI.ts
  src/pages/Project/services/projectSelectors.ts
  src/pages/Project/services/projectsReducer.ts
  stories/ProjectRow.stories.tsx
  webpack.config.js
Labels: Status: Review Needed, Type: Enhancement

#33 ⬆️ chore (npm/yarn): upgrading dependencies
  package-lock.json
  package.json
  src/dev/server.ts
  yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#31 🔨 REFACTOR: shift default exports above normal exports
  src/pages/Project/Row/services/projectRowsReducer.ts
  src/pages/Project/services/projectsReducer.ts
Labels: Status: Accepted, Type: Enhancement

#35 📚 DOCS (readme): add instructions for setting up project
  README.md
Labels: Status: Accepted, Type: Documentation

#38 ✨ FEAT (project): export project models in index
  src/pages/Project/index.ts
Labels: Status: Review Needed, Type: Enhancement

#36 🔨 REFACTOR (props): move prop declaration into view component
  src/AppRoutes.tsx
  src/components/Tag/Tag.tsx
  src/components/Tag/models/TagProps.ts
  src/pages/Exhibition/Exhibition.tsx
  src/pages/Exhibition/Host/HostExhibition.tsx
  src/pages/Exhibition/Host/index.ts
  src/pages/Exhibition/Host/style.css
  src/pages/Exhibition/Role/Role.tsx
  src/pages/Exhibition/Role/index.ts
  src/pages/Exhibition/Role/models/RoleModel.ts
  src/pages/Exhibition/Role/style.css
  src/pages/Exhibition/Section/Section.tsx
  src/pages/Exhibition/Section/index.ts
  src/pages/Exhibition/Section/models/SectionModel.ts
  src/pages/Exhibition/Section/style.css
  src/pages/Exhibition/index.ts
  src/pages/Exhibition/models/ExhibitionModel.ts
  src/pages/Exhibition/style.css
  src/pages/Exhibitions/Exhibitions.tsx
  src/pages/Exhibitions/Role/Role.tsx
  src/pages/Exhibitions/Role/index.ts
  src/pages/Exhibitions/Section/index.ts
  src/pages/Exhibitions/Section/models/SectionProps.ts
  src/pages/Exhibitions/Section/style.css
  src/pages/Exhibitions/index.ts
  src/pages/Project/ProjectPreviewLayout.tsx
  src/pages/Project/models/ProjectProps.ts
  src/services/store.ts
Labels: Status: Accepted, Type: Enhancement

#40 ✨ FEAT (project): add thumbnail to project preview
  src/dev/server.ts
  src/pages/Project/Project.tsx
  src/pages/Project/ProjectPreviewLayout.tsx
  src/pages/Project/models/ProjectModel.ts
Labels: Status: Accepted, Type: Enhancement

#39 ➕📦️ ADD: add Jest dependency
  .github/workflows/ci-npm.yml
  jest.config.js
  package-lock.json
  package.json
  src/App.test.tsx
Labels: Status: Accepted, Type: Enhancement

#41 ✨ FEAT (project/row): add text styling for row
  src/dev/server.ts
  src/pages/Project/Project.tsx
  src/pages/Project/Row/ProjectRowText.tsx
  src/pages/Project/Row/models/ProjectRowTextModel.ts
Labels: Status: Accepted, Type: Enhancement

#44 ⬆️ chore (npm): update packages
  package-lock.json
  package.json
Labels: Status: Accepted, Type: Enhancement
